[package]
name = "application"
version.workspace = true
authors.workspace = true
edition = "2021"

[dev-dependencies]
mockall = "0.11"

[dependencies]
log = { workspace = true }
tokio = { workspace = true }
async-trait = "0.1.68"
futures = "0.3.28"
